ci:
  autoupdate_schedule: monthly

fail_fast: true

repos:
  # Commit message formatting check
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.28.0
    hooks:
      - id: commitizen
        stages: [commit-msg]

  # Linting and Formatting with Ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.4
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --show-fixes]
      - id: ruff-format

  #  Python Static Type Checking
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        args: [--pretty]
        description: run mypy in current environment (with typed imports) against modified .py files
        entry: mypy
        language: python
        files: .*.py$
        verbose: true

  #  Check pdm.lock is up-to-date with pyproject.toml
  - repo: https://github.com/pdm-project/pdm
    rev: 2.18.1
    hooks:
      - id: pdm-lock-check
      - id: pdm-sync

  - repo: local
    hooks:
    - id: pytest
      name: pytest
      entry: pdm run tests
      language: python
      types: [python]
      pass_filenames: false
      always_run: true
